allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects { subproject ->
    subproject.plugins.withId("com.android.library") {
        def androidExt = subproject.extensions.findByName("android")
        if (androidExt != null && androidExt.hasProperty("namespace") && (androidExt.namespace == null || androidExt.namespace == "")) {
            androidExt.namespace = "com.curiousoft.${subproject.name.replace('-', '_')}"
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
